Xuanwo/hdrs

- Cargo.toml
- src/client.rs
- src/file.rs
- src/file_info.rs
- src/lib.rs
- src/stream_builder.rs
> feat: Implement stat and readdir

- .github/actions/check/action.yml
- .github/workflows/ci.yml
> ci: Fix libhdfs not found

- .gitignore
- CONTRIBUTING.md
- README.md
- rust-toolchain.toml
- rustfmt.toml
- src/client.rs
- src/file.rs
- src/file_info.rs
- src/lib.rs
- src/stream_builder.rs
> docs: Add docs for all public API

- .github/workflows/ci.yml
- Cargo.toml
- src/client.rs
- src/file.rs
- src/lib.rs
- tests/main.rs
> tests: Enable integration tests

- Cargo.toml
- README.md
> Bump to version 0.0.2

- Cargo.toml
- src/file.rs
- tests/main.rs
> feat: Implement async file support for futures and tokio

- src/client.rs
- src/file.rs
> feat: Mark Client ans File as thread-safe

- src/client.rs
- src/lib.rs
- src/metadata.rs
> refactor: Rename FileInfo into Metadata

- src/client.rs
- tests/main.rs
> refactor: Rename client.stat to client.metadata

- src/metadata.rs
- tests/main.rs
> refactor: Use rust style getter

- src/client.rs
- tests/main.rs
> refactor: Rename mkdir to create_dir

- src/client.rs
- src/lib.rs
- tests/main.rs
> refactor: Split delete into remove_file and remove_dir

- src/client.rs
- src/lib.rs
- src/readdir.rs
> feat: Return Readdir struct instead of vector

- src/client.rs
- src/file.rs
- src/lib.rs
- tests/main.rs
> feat: Implement OpenOptions to replace client.open

- Cargo.toml
- README.md
> Bump to version 0.1.0

- src/lib.rs
> feat: Make OpenOptions public

- .github/workflows/ci.yml
- src/metadata.rs
- tests/main.rs
> feat: Trim host from hdfs path

- Cargo.toml
> Bump to version 0.1.3

- Cargo.toml
> Bump to version 0.1.4

- src/client.rs
- src/file.rs
- src/metadata.rs
- tests/main.rs
> refactor: Make clippy happy

- Cargo.toml
> Bump version to v0.1.5

- Cargo.toml
> Bump to version 0.1.6

- README.md
- src/client.rs
- src/file.rs
> feat: Implement seek to end support

- Cargo.toml
> Bump to version 0.1.7

- .github/workflows/ci.yml
- Cargo.toml
- src/async_file.rs
- src/client.rs
- src/file.rs
- src/lib.rs
- src/open_options.rs
> feat: Implement async support

- Cargo.toml
> Bump to version 0.2.0

- src/file.rs
Close https://github.com/Xuanwo/hdrs/issues/108
> fix: HDFS doesn't support seek from end
